resolver: lts-18.6

packages:
- .
- ./lib/nsc-core
- ./lib/nsc-parser
- ./lib/nsc-typechecker
- ./lib/nsc-pretty
- ./lib/nsc-flags
- ./lib/nsc-codegen
- ./lib/elfgen

extra-deps:
- git: https://github.com/mesabloo/diagnose.git
  commit: 26f5639dc567d21e1cfc9d1c9f6f6b3915e6a88a # v1.5.5


nix:
    shell-file: stack.nix

flags:
  diagnose:
    megaparsec-compat: true
