resolver: lts-16.10

packages:
- .
- ./lib/nsc-core
- ./lib/nsc-parser
- ./lib/nsc-typechecker
- ./lib/nsc-pretty
- ./lib/nsc-flags
- ./lib/nsc-codegen
- ./lib/elfgen

extra-deps:
- git: https://github.com/mesabloo/diagnose.git


nix:
    shell-file: stack.nix
